In [ ]:

from google.colab import files
uploaded=files.upload()

Saving bangalore_tech_salaries.csv to bangalore_tech_salaries.csv

TASK 1 – Load and Inspect Dataset

In [ ]:
# Import required libraries

import pandas as pd
import numpy as np

In [ ]:
# Load dataset

df = pd.read_csv("bangalore_tech_salaries.csv")

inspect dataset

In [ ]:
# Display first five rows

df.head()

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
0,BLR0065,DS,6,49.4,32.4 LPA,Ola,Unicorn,"JIRA, JavaScript, Spring Boot, Figma, NumPy, A...",HSR Layout,Tier-1,2022,Remote
1,BLR0080,DevOps,0,9.7,NaN,Walmart Labs,MNC,"Tableau, Python, Figma, JavaScript, TensorFlow",Electronic City,2,2024,Remote
2,BLR0166,SDE Backend,6,"3,360,000",24.2 LPA,Postman,Mid-size,"Agile, Excel, GCP, MongoDB, Java, ML",Whitefield,Tier-1,2023,Hybrid
3,BLR0219,SDE Frontend,8,41.4 LPA,30.3,Amazon India,MNC,"PyTorch, Redis, System Design",MG Road,Tier-2,2022,Work from Office
4,BLR0491,Product Lead,5,"3,640,000",30.6 LPA,QuickPay AI,early-stage,"Tableau, Deep Learning, Agile",Whitefield,Tier-2,2023,Onsite

In [ ]:
# Display first five rows

df.tail()

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
1010,BLR0824,Product Designer,2,17.6,12.4,Zoho,Mid-size,"React, SQL, ML, Deep Learning, Java",Jayanagar,Tier-2,2022,WFH
1011,BLR0792,Product Lead,4,₹40.2 LPA,26.6,HCL,MNC,"Excel, Java, Deep Learning, Python, JavaScript",Whitefield,Tier 2,2021,Work from Office
1012,BLR0209,BI Analyst,1,8.6 LPA,6.0 LPA,EdMint,Early-stage,"PyTorch, System Design, MongoDB, JIRA, PowerBI...",NaN,2,2024,Hybrid
1013,BLR0788,PM,2,27.6,17.4,Zomato,Unicorn,"Azure, Kafka, Excel",Bellandur,Tier-3,2023,Remote
1014,BLR0905,DA,4,₹20.3 LPA,15.4 LPA,Capgemini,MNC,"Deep Learning, JavaScript, NumPy",Marathahalli,Tier 2,2020,WFH

In [ ]:
# Display dataset shape

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 1015
Columns : 12

In [ ]:
# Display column names

print(df.columns)

Index(['Employee_ID', 'Role ', 'years_exp', 'Current_CTC', 'Previous_CTC',
       'Company', 'company_TYPE', 'Skills', 'Location', 'Education_Tier',
       'Joining_Year', 'Work_Mode'],
      dtype='object')

In [ ]:
# Display information about dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     1015 non-null   object
 1   Role            1015 non-null   object
 2   years_exp       1015 non-null   int64
 3   Current_CTC     1015 non-null   object
 4   Previous_CTC    815 non-null    object
 5   Company         1015 non-null   object
 6   company_TYPE    1015 non-null   object
 7   Skills          988 non-null    object
 8   Location        995 non-null    object
 9   Education_Tier  1015 non-null   object
 10  Joining_Year    1015 non-null   int64
 11  Work_Mode       1015 non-null   object
dtypes: int64(2), object(10)
memory usage: 95.3+ KB

In [ ]:
# Display data types

df.dtypes

Employee_ID       object
Role              object
years_exp          int64
Current_CTC       object
Previous_CTC      object
Company           object
company_TYPE      object
Skills            object
Location          object
Education_Tier    object
Joining_Year       int64
Work_Mode         object
dtype: object

In [ ]:
# Check missing values

df.isnull().sum()

Employee_ID         0
Role                0
years_exp           0
Current_CTC         0
Previous_CTC      200
Company             0
company_TYPE        0
Skills             27
Location           20
Education_Tier      0
Joining_Year        0
Work_Mode           0
dtype: int64

In [ ]:
# Check duplicate rows

df.duplicated().sum()

np.int64(15)

In [ ]:
# Statistical summary

df.describe(include="all")

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
count,1015,1015,1015.000000,1015,815,1015,1015,988,995,1015,1015.000000,1015
unique,1000,42,NaN,702,437,36,11,973,11,12,NaN,6
top,BLR0331,BA,NaN,11.7,15.4,Chargebee,MNC,"JavaScript, Agile, PostgreSQL, Azure, ML, Powe...",Electronic City,2,NaN,Hybrid
freq,2,43,NaN,5,8,44,319,2,106,141,NaN,179
mean,NaN,NaN,3.429557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.698522,NaN
std,NaN,NaN,2.558721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.308351,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN
25%,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,NaN
50%,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN
max,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN

In [ ]:
# Print dataset summary

print("="*60)
print("DATASET SUMMARY")
print("="*60)

print(f"Total Rows : {df.shape[0]}")
print(f"Total Columns : {df.shape[1]}")

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

============================================================
DATASET SUMMARY
============================================================
Total Rows : 1015
Total Columns : 12

Missing Values
Employee_ID         0
Role                0
years_exp           0
Current_CTC         0
Previous_CTC      200
Company             0
company_TYPE        0
Skills             27
Location           20
Education_Tier      0
Joining_Year        0
Work_Mode           0
dtype: int64

Duplicate Rows : 15

In [ ]:
# 3.5
bins=[0,2,4,6,100]
labeals=

task 2- data cleaning

In [ ]:
# we create copy of the dataset

clean_df = df.copy()

In [ ]:
# the Convert column names to lowercase

clean_df.columns = clean_df.columns.str.lower()

#after that we Replace spaces with underscore

clean_df.columns = clean_df.columns.str.replace(" ", "_")

print(clean_df.columns)

Index(['employee_id', 'role_', 'years_exp', 'current_ctc', 'previous_ctc',
       'company', 'company_type', 'skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

In [ ]:
# Convert to proper case

clean_df["company_type"] = clean_df["company_type"].str.title()

print(clean_df["company_type"].value_counts())

company_type
Mnc            348
Mid-Size       261
Unicorn        207
Early-Stage    199
Name: count, dtype: int64

In [ ]:
clean_df["current_ctc"] = clean_df["current_ctc"].str.replace("₹","")
clean_df["current_ctc"] = clean_df["current_ctc"].str.replace("LPA","")
clean_df["current_ctc"] = clean_df["current_ctc"].str.replace(",","")
clean_df["current_ctc"] = clean_df["current_ctc"].astype(float)

In [ ]:
clean_df["previous_ctc"] = clean_df["previous_ctc"].str.replace("₹","")
clean_df["previous_ctc"] = clean_df["previous_ctc"].str.replace("LPA","")
clean_df["previous_ctc"] = clean_df["previous_ctc"].str.replace(",","")

clean_df["previous_ctc"] = pd.to_numeric(
    clean_df["previous_ctc"],
    errors="coerce"
)

In [ ]:
clean_df = clean_df.drop_duplicates()

print(clean_df.shape)

(1000, 12)

In [ ]:
clean_df.isnull().sum()

employee_id         0
role_               0
years_exp           0
current_ctc         0
previous_ctc      194
company             0
company_type        0
skills             27
location           19
education_tier      0
joining_year        0
work_mode           0
dtype: int64

In [ ]:
clean_df.dtypes

employee_id        object
role_              object
years_exp           int64
current_ctc       float64
previous_ctc      float64
company            object
company_type       object
skills             object
location           object
education_tier     object
joining_year        int64
work_mode          object
dtype: object

In [ ]:
print(clean_df.head())

  employee_id         role_  years_exp  current_ctc  previous_ctc  \
0     BLR0065            DS          6         49.4          32.4
1     BLR0080        DevOps          0          9.7           NaN
2     BLR0166   SDE Backend          6    3360000.0          24.2
3     BLR0219  SDE Frontend          8         41.4          30.3
4     BLR0491  Product Lead          5    3640000.0          30.6

        company company_type  \
0           Ola      Unicorn
1  Walmart Labs          Mnc
2       Postman     Mid-Size
3  Amazon India          Mnc
4   QuickPay AI  Early-Stage

                                              skills         location  \
0  JIRA, JavaScript, Spring Boot, Figma, NumPy, A...       HSR Layout
1     Tableau, Python, Figma, JavaScript, TensorFlow  Electronic City
2               Agile, Excel, GCP, MongoDB, Java, ML       Whitefield
3                      PyTorch, Redis, System Design          MG Road
4                      Tableau, Deep Learning, Agile       Whitefield

  education_tier  joining_year         work_mode
0         Tier 1          2022            Remote
1         Tier 2          2024            Remote
2         Tier 1          2023            Hybrid
3         Tier 2          2022  Work from Office
4         Tier 2          2023            Onsite

## Task 3.1 – Salary Distribution by Role

In [ ]:
#for the list of column present
print(clean_df.columns)

Index(['employee_id', 'role_', 'years_exp', 'current_ctc', 'previous_ctc',
       'company', 'company_type', 'skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

In [ ]:
#This will show the actual column names
clean_df.rename(columns={"role_": "role"}, inplace=True)

print(clean_df.columns)

Index(['employee_id', 'role', 'years_exp', 'current_ctc', 'previous_ctc',
       'company', 'company_type', 'skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

/tmp/ipykernel_3078/3365647571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df.rename(columns={"role_": "role"}, inplace=True)

In [ ]:
# Median, Mean, Min and Max salary for each role
role_salary = clean_df.groupby("role")["current_ctc"].agg(
    ["median", "mean", "min", "max"]
)

role_salary = role_salary.sort_values(by="median", ascending=False)

print(role_salary)

                           median           mean   min        max
role
PM                          40.45  910384.453571  13.8  5690000.0
Sr PM                       40.05  367339.419231  10.8  4730000.0
Product Lead                34.10  662927.316129  12.0  4370000.0
Product Manager             32.10  310031.285185  14.2  5230000.0
ML Engineer                 31.40  174867.296774  10.0  2220000.0
Backend Engineer            31.10  439437.917647   9.9  4040000.0
DS                          29.30  388822.200000  10.9  2730000.0
Data Science Engineer       28.15  364358.046667  14.3  2900000.0
Frontend Developer          26.95  341270.191667  11.0  2930000.0
UI/UX                       26.90  147411.395652   6.2  1590000.0
Site Reliability Engineer   26.80  494260.815152   9.9  3270000.0
Data Scientist              26.60  565148.248718  11.7  4170000.0
SDE Frontend                26.15  243518.570000   6.7  3060000.0
SDE Full-Stack              25.45  247526.093750  12.5  2890000.0
FE                          25.30      24.108333  11.5       31.1
SDE FS                      25.25  710854.837500  11.5  7090000.0
BE                          25.20  301598.194737  10.9  2380000.0
Infra Engineer              25.20   59522.015000   9.2  1190000.0
UX Designer                 25.10  253178.578947   6.6  1839999.0
Fullstack Dev               24.90  350732.600000  12.4  2560000.0
SRE                         24.85  300021.278571   8.8  4840000.0
BA                          24.50  603187.500000   7.6  5270000.0
SDE Backend                 24.10  333497.691304   9.1  3360000.0
Full Stack Engineer         23.20  357294.545455  12.9  4980000.0
Product Designer            22.60  199149.969565  12.5  1210000.0
Analytics Engineer          22.55  254563.818182   9.1  2610000.0
Business Systems Analyst    22.20  132520.746875   6.8  3090000.0
SDE-Backend                 22.10   97165.909524   9.3  2039999.0
Frontend Engineer           21.80  501068.473684   8.1  3650000.0
DevOps Engineer             21.80  432521.087500   9.8  5610000.0
Frontend Dev                21.75  205023.094444  14.1  2800000.0
Backend Dev                 20.60  145808.415789   9.2  1650000.0
UI Designer                 20.55  357516.350000   8.6  2940000.0
DevOps                      20.05  339562.109091   9.7  2089999.0
Business Analyst            20.00  211161.322857   6.8  2430000.0
FullStack                   19.75  129020.280000   8.9  1370000.0
Backend Developer           18.90   88018.746667   8.0  1320000.0
Designer                    18.85  387158.189286   7.1  4380000.0
BI Analyst                  17.80  566082.442857   5.2  3629999.0
SDE-Frontend                17.70  264181.158333  12.8  1960000.0
DA                          16.90  179274.118519   5.9  2790000.0
Data Analyst                16.90  193928.795652   5.6  1689999.0

In [ ]:
#to find highest paying tole and lowest paying role
print("Highest Paying Role")
print(role_salary.head(1))

Highest Paying Role
      median           mean   min        max
role
PM     40.45  910384.453571  13.8  5690000.0

In [ ]:
print("Lowest Paying Role")
print(role_salary.tail(1))

Lowest Paying Role
              median           mean  min        max
role
Data Analyst    16.9  193928.795652  5.6  1689999.0

task 3.2-Salary Based on Experience

In [ ]:
# Select only Backend employees

backend = clean_df[clean_df["role"]=="SDE Backend"]

# Create experience groups

backend["experience"] = pd.cut(
    backend["years_exp"],
    bins=[0,1,3,5,100],
    labels=["0-1","2-3","4-5","6+"]
)

# Find median salary

print(backend.groupby("experience")["current_ctc"].median())

experience
0-1    16.35
2-3    23.30
4-5    27.60
6+     46.00
Name: current_ctc, dtype: float64

/tmp/ipykernel_3078/907549934.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  backend["experience"] = pd.cut(
/tmp/ipykernel_3078/907549934.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(backend.groupby("experience")["current_ctc"].median())

task 3.3-Skill Premium

In [ ]:
skills = ["AWS","ML","System Design","Kubernetes"]
# List of skills to analyze
# for Loop for each skill one by one

for skill in skills:

    yes = clean_df[
        clean_df["skills"].fillna("").str.contains(skill)
    ]["current_ctc"].median()

    no = clean_df[
        ~clean_df["skills"].fillna("").str.contains(skill)
    ]["current_ctc"].median()

    print(skill)
    print("With Skill :", yes)
    print("Without Skill :", no)
    print()

AWS
With Skill : 27.25
Without Skill : 24.299999999999997

ML
With Skill : 27.0
Without Skill : 24.3

System Design
With Skill : 26.0
Without Skill : 24.45

Kubernetes
With Skill : 25.6
Without Skill : 24.45

task 3.4-compare salary

In [ ]:
backend = clean_df[clean_df["role"]=="SDE Backend"]

print(
    backend.groupby("company_type")["current_ctc"].median()
)

company_type
Early-Stage         31.8
Mid-Size       1370000.0
Mnc                 21.1
Unicorn             26.0
Name: current_ctc, dtype: float64

In [ ]:
# Create experience groups

clean_df["experience"] = pd.cut(
    clean_df["years_exp"],
    bins=[0,1,3,5,100],
    labels=["0-1","2-3","4-5","6+"]
)

# Median salary of each group

clean_df["group_salary"] = clean_df.groupby(
    ["role","company_type","experience"]
)["current_ctc"].transform("median")

# Salary difference

clean_df["gap"] = clean_df["current_ctc"] - clean_df["group_salary"]

# Show lowest paid employees

underpaid = clean_df.sort_values("gap")

print(
    underpaid[
        ["employee_id","role","current_ctc","gap"]
    ].head(10)
)

    employee_id                 role  current_ctc         gap
374     BLR0332                   BA         46.0 -2919954.00
389     BLR0773                   BA         35.9 -2634982.05
376     BLR0204       Data Scientist         29.5 -2589970.50
48      BLR0718  Full Stack Engineer         41.1 -2489979.45
617     BLR0125                  SRE         49.5 -2419975.25
981     BLR0681      DevOps Engineer         19.4 -2209980.60
330     BLR0366             Designer         25.2 -2189987.40
385     BLR0966                   PM         39.7 -1974980.15
221     BLR0458    Frontend Engineer         39.4 -1824980.30
609     BLR0617                   PM         30.5 -1809984.75

/tmp/ipykernel_3078/783830127.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["experience"] = pd.cut(
/tmp/ipykernel_3078/783830127.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  clean_df["group_salary"] = clean_df.groupby(
/tmp/ipykernel_3078/783830127.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["group_salary"] = clean_df.groupby(
/tmp/ipykernel_3078/783830127.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["gap"] = clean_df["current_ctc"] - clean_df["group_salary"]

Task 4 – Build the Final Printed Repor

In [ ]:
print(clean_df.columns.tolist())

['employee_id', 'role', 'years_exp', 'current_ctc', 'previous_ctc', 'company', 'company_type', 'skills', 'location', 'education_tier', 'joining_year', 'work_mode', 'experience', 'group_salary', 'gap']

In [ ]:
print("="*70)
print("        BANGALORE TECH SALARY DECODER")
print("        Built by: Vaishnavi More")
print("="*70)

print("\nDataset Information")
print("-"*70)
print("Total Employees :", len(clean_df))
print("Total Roles :", clean_df["role"].nunique())
print("Total Companies :", clean_df["company"].nunique())

print("\nMEDIAN CTC BY ROLE")
print("-"*70)
print(role_salary["median"])

print("\nSDE BACKEND MEDIAN SALARY BY EXPERIENCE")
print("-"*70)


print("\nCOMPANY TYPE MEDIAN SALARY")
print("-"*70)

print("\nTOP 5 UNDERPAID PROFESSIONALS")
print("-"*70)

print(
    underpaid[
        [
            "employee_id",
            "role",
            "company_type",
            "current_ctc",
            "gap"
        ]
    ].head(5)
)

print("="*70)
print("End of Report")
print("="*70)

======================================================================
        BANGALORE TECH SALARY DECODER
        Built by: Vaishnavi More
======================================================================

Dataset Information
----------------------------------------------------------------------
Total Employees : 1000
Total Roles : 42
Total Companies : 36

MEDIAN CTC BY ROLE
----------------------------------------------------------------------
role
PM                           40.45
Sr PM                        40.05
Product Lead                 34.10
Product Manager              32.10
ML Engineer                  31.40
Backend Engineer             31.10
DS                           29.30
Data Science Engineer        28.15
Frontend Developer           26.95
UI/UX                        26.90
Site Reliability Engineer    26.80
Data Scientist               26.60
SDE Frontend                 26.15
SDE Full-Stack               25.45
FE                           25.30
SDE FS                       25.25
BE                           25.20
Infra Engineer               25.20
UX Designer                  25.10
Fullstack Dev                24.90
SRE                          24.85
BA                           24.50
SDE Backend                  24.10
Full Stack Engineer          23.20
Product Designer             22.60
Analytics Engineer           22.55
Business Systems Analyst     22.20
SDE-Backend                  22.10
Frontend Engineer            21.80
DevOps Engineer              21.80
Frontend Dev                 21.75
Backend Dev                  20.60
UI Designer                  20.55
DevOps                       20.05
Business Analyst             20.00
FullStack                    19.75
Backend Developer            18.90
Designer                     18.85
BI Analyst                   17.80
SDE-Frontend                 17.70
DA                           16.90
Data Analyst                 16.90
Name: median, dtype: float64

SDE BACKEND MEDIAN SALARY BY EXPERIENCE
----------------------------------------------------------------------

COMPANY TYPE MEDIAN SALARY
----------------------------------------------------------------------

TOP 5 UNDERPAID PROFESSIONALS
----------------------------------------------------------------------
    employee_id                 role company_type  current_ctc         gap
374     BLR0332                   BA     Mid-Size         46.0 -2919954.00
389     BLR0773                   BA      Unicorn         35.9 -2634982.05
376     BLR0204       Data Scientist  Early-Stage         29.5 -2589970.50
48      BLR0718  Full Stack Engineer     Mid-Size         41.1 -2489979.45
617     BLR0125                  SRE      Unicorn         49.5 -2419975.25
======================================================================
End of Report
======================================================================

task 5

In [ ]:
print("="*60)
print("               TASK 5 : KEY INSIGHTS")
print("="*60)

print("1. The highest-paying role is __________ with a median salary of _____ LPA.")

print("\n2. SDE Backend salaries increase as experience increases, showing strong salary growth with experience.")

print("\n3. __________ provides the highest salary premium, making it one of the most valuable skills for better salary opportunities.")

print("="*60)

============================================================
               TASK 5 : KEY INSIGHTS
============================================================
1. The highest-paying role is __________ with a median salary of _____ LPA.

2. SDE Backend salaries increase as experience increases, showing strong salary growth with experience.

3. __________ provides the highest salary premium, making it one of the most valuable skills for better salary opportunities.
============================================================

task 6

In [ ]:
# Task 6 - Final Review

print("="*60)
print("        PROJECT REVIEW")
print("="*60)

print(" Task 1 : Load and Inspect - Completed")
print(" Task 2 : Data Cleaning - Completed")
print("Task 3 : Business Questions - Completed")
print("Task 4 : Final Report - Completed")
print(" Task 5 : Key Insights - Completed")
print(" Task 6 : Code Review - Completed")

print("="*60)
print("Project is Ready for Submission")
print("="*60)

============================================================
        PROJECT REVIEW
============================================================
 Task 1 : Load and Inspect - Completed
 Task 2 : Data Cleaning - Completed
Task 3 : Business Questions - Completed
Task 4 : Final Report - Completed
 Task 5 : Key Insights - Completed
 Task 6 : Code Review - Completed
============================================================
Project is Ready for Submission
============================================================